[package]
name = "domain-workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde_json = "1.0"
storage-core = { path = "../storage-core" }

[dev-dependencies]
storage-core = { path = "../storage-core" }

[lints]
workspace = true
